routes:
  /blog/tags: blog/taxonomies
  /search: search
  /users: user/index
  /users/{username}: user/profile
  /account: user/account
  /login: auth/login
  /register: auth/register
  /forgot-password: auth/password-forgot
  /reset-password: auth/password-reset
collections:
  blog: '/blog/{slug}'
  casestudies: 'case-studies/{slug}'
  benefits: 'benefits/{slug}'
  features: 'features/{slug}'
  modules: 'features/modules/{slug}'
  events: 'events/{slug}'
taxonomies:
  tags: '/blog/tags/{slug}'
  categories: '/blog/categories/{slug}'
redirect: [ ]
vanity: [ ]
